/**
 * Hand-curated shorthand communities actually use, mapped to the canonical
 * catalogue title. No automatic alias discovery is attempted at v1 — a wrong
 * alias is a precision failure, and precision is the property being defended.
 *
 * Keys are matched after normalization, so case and punctuation here are
 * cosmetic. Values must match a catalogue title (also after normalization);
 * an alias whose target is absent from the catalogue is dropped at build time.
 */
export const CURATED_ALIASES: Readonly<Record<string, string>> = {
  // Abbreviations
  botw: 'The Legend of Zelda: Breath of the Wild',
  totk: 'The Legend of Zelda: Tears of the Kingdom',
  tw3: 'The Witcher 3: Wild Hunt',
  'the witcher 3': 'The Witcher 3: Wild Hunt',
  witcher3: 'The Witcher 3: Wild Hunt',
  hk: 'Hollow Knight',
  bg3: "Baldur's Gate 3",
  'baldurs gate 3': "Baldur's Gate 3",
  ds1: 'DARK SOULS: REMASTERED',
  ds3: 'DARK SOULS III',
  'ds 3': 'DARK SOULS III',
  er: 'ELDEN RING',
  'elden ring': 'ELDEN RING',
  sekiro: 'Sekiro: Shadows Die Twice',
  bb: 'Bloodborne',
  rdr2: 'Red Dead Redemption 2',
  'rdr 2': 'Red Dead Redemption 2',
  gta5: 'Grand Theft Auto V',
  'gta 5': 'Grand Theft Auto V',
  gtav: 'Grand Theft Auto V',
  csgo: 'Counter-Strike: Global Offensive',
  cs2: 'Counter-Strike 2',
  tf2: 'Team Fortress 2',
  'l4d2': 'Left 4 Dead 2',
  ff7: 'FINAL FANTASY VII',
  ffvii: 'FINAL FANTASY VII',
  ff14: 'FINAL FANTASY XIV Online',
  ffxiv: 'FINAL FANTASY XIV Online',
  mgs: 'METAL GEAR SOLID',
  'nier automata': 'NieR:Automata',
  nier: 'NieR:Automata',
  poe: 'Path of Exile',
  poe2: 'Path of Exile 2',
  dbd: 'Dead by Daylight',
  'dead cells': 'Dead Cells',
  kcd: 'Kingdom Come: Deliverance',
  kcd2: 'Kingdom Come: Deliverance II',
  'stardew': 'Stardew Valley',
  'sdv': 'Stardew Valley',
  'satisfactory': 'Satisfactory',
  'factorio': 'Factorio',
  'rimworld': 'RimWorld',
  'cyberpunk': 'Cyberpunk 2077',
  'cp2077': 'Cyberpunk 2077',
  'ac odyssey': "Assassin's Creed Odyssey",
  'ac origins': "Assassin's Creed Origins",
  'dmc5': 'Devil May Cry 5',
  're4': 'Resident Evil 4',
  're2': 'Resident Evil 2',
  'mhw': 'Monster Hunter: World',
  'mh world': 'Monster Hunter: World',
  'mhr': 'Monster Hunter Rise',
  'silksong': 'Hollow Knight: Silksong',
  'oot': 'The Legend of Zelda: Ocarina of Time',
  'ttyd': 'Paper Mario: The Thousand-Year Door',
  'smo': 'Super Mario Odyssey',
  'botw2': 'The Legend of Zelda: Tears of the Kingdom',
  'p5r': 'Persona 5 Royal',
  'p5': 'Persona 5 Royal',
  'p4g': 'Persona 4 Golden',
  'dq11': 'DRAGON QUEST XI S: Echoes of an Elusive Age',
  'xc2': 'Xenoblade Chronicles 2',
  'xc3': 'Xenoblade Chronicles 3',
};
