/**
 * Game titles that are also ordinary English words or phrases.
 *
 * These are not excluded from the dictionary — they are real games and people
 * genuinely recommend them. They are marked *ambiguous*, which means a match
 * only counts when the surrounding text supplies evidence that a title was
 * meant: title-case or all-caps capitalisation, or explicit quoting.
 *
 * Entries are stored in normalized form (see `normalizeTitle`).
 */
export const AMBIGUOUS_TITLES: ReadonlySet<string> = new Set([
  // Single ordinary words that are well-known titles.
  'limbo',
  'portal',
  'control',
  'journey',
  'inside',
  'braid',
  'fez',
  'rust',
  'prey',
  'grounded',
  'raft',
  'spore',
  'bastion',
  'transistor',
  'everything',
  'worms',
  'trine',
  'risk',
  'doom',
  'rage',
  'evolve',
  'destiny',
  'division',
  'anthem',
  'brink',
  'smite',
  'rift',
  'tera',
  'blade',
  'hunt',
  'dust',
  'drift',
  'flow',
  'flower',
  'unravel',
  'observation',
  'soma',
  'alien',
  'catherine',
  'persona',
  'rime',
  'forced',
  'torment',
  'quest',
  'legend',
  'hero',
  'myth',
  'saga',
  'arena',
  'fall',
  'rise',
  'dawn',
  'dusk',
  'void',
  'core',
  'echo',
  'pulse',
  'drive',
  'sky',
  'ocean',
  'island',
  'tower',
  'bridge',
  'gate',
  'star',
  'moon',
  'fire',
  'storm',
  'wave',
  'stone',
  'iron',
  'steel',
  'gold',
  'silver',
  'shelter',
  'home',
  'refuge',
  'among',
  'spirit',
  'ghost',
  'shadow',
  'reflection',
  'balance',
  'pitfall',
  'contrast',
  'closure',
  'gravity',
  'osmos',
  'antichamber',
  'reset',
  'recompile',
  'induction',
  'manifold',
  'exit',
  'entry',
  'descent',
  'ascent',
  'outcast',
  'renegade',
  'sacrifice',
  'darkness',
  'silence',
  'reverie',
  'solace',
  'haven',
  'refunct',

  // Ordinary phrases that are also titles.
  'the forest',
  'the crew',
  'the room',
  'the witness',
  'the division',
  'the hunter',
  'the long dark',
  'the beginner',
  'gone home',
  'state of mind',
  'dead end',
  'first light',
  'the end',
  'the game',
  'the last one',
  'no man',
  'the swapper',
  'the talos principle',
]);

export function isAmbiguousTitle(normalized: string): boolean {
  return AMBIGUOUS_TITLES.has(normalized);
}
