/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/app/theme.ts
 * Command: astryx theme build src/app/theme.ts --out src/app/theme.generated/grs.css
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

/// <reference path="./grs.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const grsTheme: DefinedTheme;
